// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/proto/cart.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int32 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *ViewCartRequest) Reset() {
	*x = ViewCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCartRequest) ProtoMessage() {}

func (x *ViewCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCartRequest.ProtoReflect.Descriptor instead.
func (*ViewCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{0}
}

func (x *ViewCartRequest) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type CartItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductDetailID string `protobuf:"bytes,1,opt,name=ProductDetailID,proto3" json:"ProductDetailID,omitempty"`
	Image           string `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	ModelName       string `protobuf:"bytes,3,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	Price           uint32 `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	Size            string `protobuf:"bytes,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Colour          string `protobuf:"bytes,6,opt,name=Colour,proto3" json:"Colour,omitempty"`
	BrandName       string `protobuf:"bytes,7,opt,name=BrandName,proto3" json:"BrandName,omitempty"`
	Quantity        uint32 `protobuf:"varint,8,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Percentage      int32  `protobuf:"varint,9,opt,name=Percentage,proto3" json:"Percentage,omitempty"`
	Total           uint32 `protobuf:"varint,10,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *CartItems) Reset() {
	*x = CartItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItems) ProtoMessage() {}

func (x *CartItems) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItems.ProtoReflect.Descriptor instead.
func (*CartItems) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartItems) GetProductDetailID() string {
	if x != nil {
		return x.ProductDetailID
	}
	return ""
}

func (x *CartItems) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CartItems) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CartItems) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItems) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CartItems) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

func (x *CartItems) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *CartItems) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItems) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *CartItems) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ViewCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     int32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Grandtotal int32        `protobuf:"varint,2,opt,name=Grandtotal,proto3" json:"Grandtotal,omitempty"`
	Items      []*CartItems `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ViewCartResponse) Reset() {
	*x = ViewCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCartResponse) ProtoMessage() {}

func (x *ViewCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCartResponse.ProtoReflect.Descriptor instead.
func (*ViewCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{2}
}

func (x *ViewCartResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ViewCartResponse) GetGrandtotal() int32 {
	if x != nil {
		return x.Grandtotal
	}
	return 0
}

func (x *ViewCartResponse) GetItems() []*CartItems {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid string `protobuf:"bytes,1,opt,name=productid,proto3" json:"productid,omitempty"`
	Userid    uint32 `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *AddCartRequest) Reset() {
	*x = AddCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartRequest) ProtoMessage() {}

func (x *AddCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartRequest.ProtoReflect.Descriptor instead.
func (*AddCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{3}
}

func (x *AddCartRequest) GetProductid() string {
	if x != nil {
		return x.Productid
	}
	return ""
}

func (x *AddCartRequest) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type AddCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Response string `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *AddCartResponse) Reset() {
	*x = AddCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartResponse) ProtoMessage() {}

func (x *AddCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartResponse.ProtoReflect.Descriptor instead.
func (*AddCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{4}
}

func (x *AddCartResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddCartResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_pkg_proto_cart_proto protoreflect.FileDescriptor

var file_pkg_proto_cart_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x29, 0x0a, 0x0f, 0x56, 0x69,
	0x65, 0x77, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x9b, 0x02, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43,
	0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x6c,
	0x6f, 0x75, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a,
	0x0a, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x22, 0x6f, 0x0a, 0x10, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x47, 0x72, 0x61, 0x6e, 0x64, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x47, 0x72, 0x61, 0x6e, 0x64, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x46, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x7e, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x72, 0x74, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x41,
	0x64, 0x64, 0x74, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64,
	0x64, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_cart_proto_rawDescOnce sync.Once
	file_pkg_proto_cart_proto_rawDescData = file_pkg_proto_cart_proto_rawDesc
)

func file_pkg_proto_cart_proto_rawDescGZIP() []byte {
	file_pkg_proto_cart_proto_rawDescOnce.Do(func() {
		file_pkg_proto_cart_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_cart_proto_rawDescData)
	})
	return file_pkg_proto_cart_proto_rawDescData
}

var file_pkg_proto_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_cart_proto_goTypes = []interface{}{
	(*ViewCartRequest)(nil),  // 0: pb.ViewCartRequest
	(*CartItems)(nil),        // 1: pb.CartItems
	(*ViewCartResponse)(nil), // 2: pb.ViewCartResponse
	(*AddCartRequest)(nil),   // 3: pb.AddCartRequest
	(*AddCartResponse)(nil),  // 4: pb.AddCartResponse
}
var file_pkg_proto_cart_proto_depIdxs = []int32{
	1, // 0: pb.ViewCartResponse.items:type_name -> pb.CartItems
	0, // 1: pb.CartService.ViewCart:input_type -> pb.ViewCartRequest
	3, // 2: pb.CartService.AddtoCart:input_type -> pb.AddCartRequest
	2, // 3: pb.CartService.ViewCart:output_type -> pb.ViewCartResponse
	4, // 4: pb.CartService.AddtoCart:output_type -> pb.AddCartResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_cart_proto_init() }
func file_pkg_proto_cart_proto_init() {
	if File_pkg_proto_cart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_cart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_cart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_cart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_cart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_cart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_cart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_cart_proto_goTypes,
		DependencyIndexes: file_pkg_proto_cart_proto_depIdxs,
		MessageInfos:      file_pkg_proto_cart_proto_msgTypes,
	}.Build()
	File_pkg_proto_cart_proto = out.File
	file_pkg_proto_cart_proto_rawDesc = nil
	file_pkg_proto_cart_proto_goTypes = nil
	file_pkg_proto_cart_proto_depIdxs = nil
}
