// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/stebinsabu13/ecommerce_microservice/api_gateway/pkg/api"
	"github.com/stebinsabu13/ecommerce_microservice/api_gateway/pkg/api/handler"
	"github.com/stebinsabu13/ecommerce_microservice/api_gateway/pkg/client"
	"github.com/stebinsabu13/ecommerce_microservice/api_gateway/pkg/config"
	"github.com/stebinsabu13/ecommerce_microservice/api_gateway/pkg/service"
)

// Injectors from wire.go:

func InitializeAPI(c *config.Config) (*api.Server, error) {
	clients, err := service.InitClient(c)
	if err != nil {
		return nil, err
	}
	authClient := client.NewauthClient(clients)
	authHandler := handler.NewUserHandler(authClient)
	productClient := client.NewProductClient(clients)
	productHandler := handler.NewProductHandler(productClient)
	cartClient := client.NewCartClient(clients)
	cartHandler := handler.NewCartHandler(cartClient)
	orderClient := client.NewOrderClient(clients)
	orderHandler := handler.NewOrderHandler(orderClient)
	server, err := api.NewServerHTTP(c, authHandler, productHandler, cartHandler, orderHandler)
	if err != nil {
		return nil, err
	}
	return server, nil
}
