// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/stebinsabu13/ecommerce_microservice/auth_service/pkg/api"
	"github.com/stebinsabu13/ecommerce_microservice/auth_service/pkg/api/service"
	"github.com/stebinsabu13/ecommerce_microservice/auth_service/pkg/client"
	"github.com/stebinsabu13/ecommerce_microservice/auth_service/pkg/config"
	"github.com/stebinsabu13/ecommerce_microservice/auth_service/pkg/db"
	"github.com/stebinsabu13/ecommerce_microservice/auth_service/pkg/repository"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	gormDB, err := db.Initdb(c)
	if err != nil {
		return nil, err
	}
	authRepo := repository.NewauthRepo(gormDB)
	cartServiceClient, err := client.InitCartClient(c)
	if err != nil {
		return nil, err
	}
	cartClient := client.NewCartClient(cartServiceClient)
	authServiceServer := service.NewauthUseCase(authRepo, cartClient)
	server, err := api.NewgrpcServe(c, authServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
