// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/stebinsabu13/ecommerce_microservice/product_service/pkg/api"
	"github.com/stebinsabu13/ecommerce_microservice/product_service/pkg/api/service"
	"github.com/stebinsabu13/ecommerce_microservice/product_service/pkg/config"
	"github.com/stebinsabu13/ecommerce_microservice/product_service/pkg/db"
	"github.com/stebinsabu13/ecommerce_microservice/product_service/pkg/repository"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	gormDB, err := db.Initdb(c)
	if err != nil {
		return nil, err
	}
	productRepo := repository.NewProductRepo(gormDB)
	productServiceServer := service.NewProductService(productRepo)
	server, err := api.NewgrpcServe(c, productServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
